### PR TITLE
Remove upstream/downstream gene consequence terms

### PR DESCRIPTION
**Pull request by nawatts**
#87 applied to the Hail 0.2 version of computed fields.

Resolves macarthur-lab/gnomadjs#384.

### CODE REVIEW

**Comment by hanars** [comment]
Is there any reason not to remove these consequences from the `CONSEQUENCE_TERMS` list completely? I feel like keeping them there is confusing/ might mess up sorting

**Comment by nawatts** [comment]
I kind of like having them there since then you can use `CONSEQUENCE_TERM_RANK_LOOKUP` on VEP output, not just `sortedTranscriptConsequences`. But I don't know that that is actually useful.

**Comment by hanars** [comment]
Maybe move them to the bottom of the list? I just find it odd that we are ranking them higher than other transcripts but also filtering them out

**Comment by nawatts** [comment]
I don't think we should change the order since it is is defined by Ensembl's estimate of severity. Which is another reason I favor leaving these two terms in the list... that way, we have the complete ranking from https://ensembl.org/info/genome/variation/prediction/predicted_data.html (though I just noticed we're missing `start_retained_variant`).

**Comment by hanars** [comment]
okay thats fine. Maybe put a comment in the code indicating where that ranking comes from then?

**Pull request merged**
